### ISSUE TITLE
is there any requirements to use the conv?

### ISSUE THREAD

**Issue by tian-2024** [BGU-CS-VIL/WTConv#1]
I tried it in data.shape [b, 1, 96, 512], and kernel =5 is ok ,but kernel is 8 is wrong
```

if __name__ == "__main__":
    x = torch.rand(2, 1, 96, 512)
    model = WTConv2d(in_channels=1, out_channels=1, kernel_size=8)
    print(model(x).shape)


RuntimeError: shape '[2, 1, 4, 48, 256]' is invalid for input of size 91080
```

**Comment by shahaffind** [comment]
I think the issue might be from the calculation of the padding.

The padding is calculated to have a similar resolution for the output of the convolution as the input (which is crucial for the convolution in the wavelet domain).

A quick fix might be using 'same' as padding in order to calculate it automatically. I will test to make sure it doesn't break anything and update the code accordingly. (you can try it sooner if you'd like :smile:)

**Comment by tian-2024** [comment]
> I think the issue might be from the calculation of the padding.
> 
> The padding is calculated to have a similar resolution for the output of the convolution as the input (which is crucial for the convolution in the wavelet domain).
> 
> A quick fix might be using 'same' as padding in order to calculate it automatically. I will test to make sure it doesn't break anything and update the code accordingly. (you can try it sooner if you'd like 😄)

Thankyou~ I feel it's an interesting work~

**Comment by shahaffind** [comment]
Thanks :)
The padding was fixed in the updated code.

**Comment by WKUANEI** [comment]
UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\Convolution.cpp:1009.)
  return F.conv2d(input, weight, bias, self.stride,
-----------------------------------------------------
I get this warning when I set the kernel_size to 4
I think we should find a way to address this warning
