### ISSUE TITLE
How to understand  the FLOP count of the WTs？

### ISSUE THREAD

**Issue by cjp02160** [BGU-CS-VIL/WTConv#2]
Hello, I am a little confused about  FLOP count of the WTs. Does the count  in the paper need to be multiplied by 4? How should we understand FLOP count of the WTs?

**Comment by shahaffind** [comment]
We break down the FLOPs calculation into 2:
1. The cost to perform WT and IWT (eq. 11)
2. the cost to perform depthwise conv in the wavelet domain. (eq. 10)

Note that each operation (WT,IWT, and conv) performed in the wavelet domain of level $i$ is performed over a resolution map that is half the size (on each spatial dimension) of the level $i-1$ (hence $N_W/2^i$ and $N_H/2^i$ in Eqs. 10 and 11).
Since we consider a naive implementation of WT,IWT as simple convolutions, we can insert the relevant parameters to Eq. 9 to calculate their cost (kernel size 2, stride 2, etc.)

If you mentioned multiplying by 4 because of the four frequency maps (LL. LH. HL. HH), it is already considered in eq. 10. (note that it only applies to the convs on the wavelet domain, as the "level 0" is the input map, and it doesn't have four frequency bands)

Hope that helps,
Shahaf

**Comment by cjp02160** [comment]
Thank you for your prompt reply, multiplying by 4 because of the four frequency maps to conv in eq. 10.However, I think it also needs to be multiplied by 4 because it generates four frequency maps in eq. 11.I don't know if I understand this correctly.Hope to get your reply！

**Comment by shahaffind** [comment]
You are totally correct! Thanks for spotting this!
It is important to note that it is still negligible - consider the example in the paper; instead of 15.7M FLOPs, it should be about 17.8M FLOPs, still far below a 31x31 conv that has 252M FLOPs.
We will update the text soon.

**Comment by cjp02160** [comment]
Ok, thank you for your reply!
