### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by lzm-01** [BGU-CS-VIL/WTConv#26]
Thank you very much for your work! However, I apologize for bothering you because I encountered an issue. When I replaced nn.Conv2d with WTConv2d, I received an error while training on multiple GPUs (two 3090 24G).Because it was working fine with multi-GPU training before the replacement. I would like to know how to resolve this issue. Thank you!

**Comment by lzm-01** [comment]
![屏幕截图 2024-10-31 112035](https://github.com/user-attachments/assets/a4063c57-1da6-43f4-ba56-8bf18453f832)

**Comment by shahaffind** [comment]
It's hard for me to debug without the complete code but I suspect the problem is with the partial function for wt and iwt.

Try to replace the following lines:
https://github.com/BGU-CS-VIL/WTConv/blob/654053f1d004dc75d3e0411aeb7020f3d566ad2c/wtconv/wtconv2d.py#L59
https://github.com/BGU-CS-VIL/WTConv/blob/654053f1d004dc75d3e0411aeb7020f3d566ad2c/wtconv/wtconv2d.py#L80

With:
```python
curr_x = wavelet.wavelet_transform(curr_x_ll, self.wt_filter)
```
```python
next_x_ll = wavelet.inverse_wavelet_transform(curr_x, self.wt_filter)
```

If it works I'll make a permanent fix to the code.

**Comment by lzm-01** [comment]
It works！Thank you！

**Comment by shahaffind** [comment]
Great, I'll update the repository soon :)
