### ISSUE TITLE
padding="same" is type error

### ISSUE THREAD

**Issue by nizhenyu0823** [BGU-CS-VIL/WTConv#29]
TypeError: conv2d(): argument 'padding' (position 5) must be tuple of ints, not str

**Comment by shahaffind** [comment]
This might be due to older version of pytorch, and can be solved by updating it (the oldest version that I know to support it is 1.9.1)

If for any reason you do not want to update it, you can calculate the padding to have an output size that matches the input size (should be kernel size devided by two rounded down)
