### ISSUE TITLE
About the ERF & bird photo

### ISSUE THREAD

**Issue by Albertchamberlain** [BGU-CS-VIL/WTConv#3]
How to make these two images？
![image](https://github.com/user-attachments/assets/0280f13a-d29f-4092-a01f-2547a27a86bf)
![image](https://github.com/user-attachments/assets/2df98cc8-a37a-48c1-aab5-c0f5e2cca291)

**Comment by shahaffind** [comment]
For the ERF please see: https://github.com/DingXiaoH/RepLKNet-pytorch/tree/main?tab=readme-ov-file#visualizing-the-effective-receptive-field
I made a slight modification to their code in order to load WTConvNeXt using the timm library, and I also had a few errors with matplotlib with their code (probably versioning) which had to be fixed.

For the bird illustration, I ran the image through MobileNetV2, which I've trained with WTConv of 2 levels. I used a breakpoint and saved the tensors of each of the steps. Note also that for visualization purposes, I've used an image of a larger resolution.
It can probably be done more easily using a script (and you can also use WTConvNeXt for it).

I'll work on adding these two scripts to the repository in the near future.

**Comment by Albertchamberlain** [comment]
Thx

**Comment by shahaffind** [comment]
I have uploaded the ERF visualization code.
The bird figure will take a bit longer, but I will close this issue for now.
