### ISSUE TITLE
AttributeError: Can't pickle local object 'wavelet_transform_init.<locals>.WaveletTransform'

### ISSUE THREAD

**Issue by fzfs** [BGU-CS-VIL/WTConv#5]
Hello, when I tried to save the model with torch.save(model,'model.pth')， it reported a AttributeError. 

AttributeError: Can't pickle local object 'wavelet_transform_init.<locals>.WaveletTransform'

**Comment by shahaffind** [comment]
Usually, you use `torch.save` on the model state_dict.
Using the timm library it can be done like this:
```python
import torch
from timm.models import create_model
from timm.utils.model import unwrap_model, get_state_dict

import WTConvNeXt


model = create_model(
    "wtconvnext_tiny",
    pretrained=False,
    num_classes=1000
)

save_state = {
    'state_dict': get_state_dict(model, unwrap_model),
}

torch.save(save_state, 't.pth')
```

If you still want to pickle the model object, the issue seems to be with the WT autograd function.
The code for it was taken from a previous project. While it solved issues with the other project, I suspect it's redundant here.
I'll work on a fix for that, make sure it doesn't break anything, and update the repository accordingly.

**Comment by fzfs** [comment]
Thank you for your kind reply~

**Comment by shahaffind** [comment]
Uploaded a fix for the pickle issue.
